### ISSUE TITLE
fix initial residual calculation for BiCGStab

### ISSUE THREAD

**Issue by scottaiton** [ThunderEgg/ThunderEgg#64]
The initial residual calculation uses the starting guess instead of the zero vector. This means that passing in a good initial guess won't reduce the number of iterations.

**Comment by donnaaboise** [comment]
So the initial residual calculation is already using a good starting guess?  Still not clear why the non-preconditioned case is crashing.  Or maybe I am missing something here ...

**Comment by scottaiton** [comment]
> So the initial residual calculation is already using a good starting guess? Still not clear why the non-preconditioned case is crashing. Or maybe I am missing something here ...

The initial residual calculation is using the starting guess, but for the stopping condition for the tolerance, it's relative to the residual for the initial guess, not relative to the residual with the zero vector

**Comment by donnaaboise** [comment]
So this sounds like what it should be doing.   I am still curious as to why there seems to be no reduction in iteration count.  Or why the non-preconditioned case doesn't seem to work.   What do you get for the non-preconditioned case?
